# --- STAGE 1 : Base (Commune) ---
FROM python:3.12-slim AS base

# Empêche Python de générer des fichiers .pyc et force l'affichage des logs en temps réel
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Installation des dépendances système minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Installation des dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# --- STAGE 2 : Development
FROM base AS dev

# On installe les outils de debug ou de test si besoin
RUN pip install --no-cache-dir debugpy pytest

COPY . .

# On lance Flask en mode debug
CMD ["flask", "--app", "immopredict.api.app", "run", "--host=0.0.0.0", "--port=5000", "--debug"]


# --- STAGE 3 : Production (Cible 'prod') ---
FROM base AS prod

# Sécurité  On crée un utilisateur non-root
RUN addgroup --system appgroup && adduser --system appuser --ingroup appgroup
USER appuser

# On ne copie que le nécessaire
COPY src/ ./src/
COPY config.py .

# En prod, on utilise un serveur robuste comme Gunicorn (pas le serveur de dev Flask)
RUN pip install --no-cache-dir gunicorn

# Port d'écoute
EXPOSE 5000

# Commande par défaut (pour l'API)
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "src.api.app:create_app()"]