server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/v1 {
        proxy_pass {{API_BASE_URL}};
    }

    location /cdn {
        proxy_pass {{CDN_BASE_URL}};
    }

}
